### ISSUE TITLE
cffi

### ISSUE THREAD

**Issue by bra-fsn** [ifduyue/python-xxhash#10]
Hi,

Using this module from pypy is very slow compared to cpython.
Would you mind rewriting it with cffi?

Thanks,

**Comment by ifduyue** [comment]
Hello,

There is a plan to write a cffi version, but I can't assure you it'll arrive soon.

**Comment by bra-fsn** [comment]
Thanks, it would be very good to have it. Apart from being slow, I get occasional pypy crashes if I'm using this module, so I had to revert to cpython, which hurts otherwise.

**Comment by ifduyue** [comment]
@bra-fsn cffi version is in branch cffi https://github.com/ifduyue/python-xxhash/tree/cffi
Please have a try and see if there are any problems.

**Comment by ifduyue** [comment]
Since `ffi.verify() is supported for backward compatibility, but is deprecated. `, I'll replace in-line API mode with out-of-line API mode.

**Comment by bra-fsn** [comment]
Thanks.
