### ISSUE TITLE
Release the GIL

### ISSUE THREAD

**Issue by thedrow** [ifduyue/python-xxhash#13]
As far as I know the standard hashlib algorithms release the GIL before computing the hash.
Is it worthwhile to release the GIL for xxhash as well or is it too fast and the cost of acquiring & releasing the GIL too great for benefiting from parallelism?

**Comment by ifduyue** [comment]
Hello,

In branch release_GIL, I wrapped xxh*_update between Py_BEGIN_ALLOW_THREADS and Py_END_ALLOW_THREADS.
In a single-thread program, there is not much performance gain.
Going to test it in a multi-thread environment.

**Comment by ifduyue** [comment]
@thedrow I've tested xxhash running in multi threads. The result seems to be varied by different input length. Given large input, releasing GIL is faster; Given small input, not releasing GIL is faster.

**Comment by ifduyue** [comment]
Large input here means greater than 20000 bytes

**Comment by thedrow** [comment]
That sounds reasonable. Can you provide the benchmarks? I can test on my own laptop as well to see if there's a difference.

**Comment by ifduyue** [comment]
https://gist.github.com/ifduyue/987cfd1ae9cb1ec3447c08c738e324c1

**Comment by ifduyue** [comment]
According to the tests, I'm not going to make any changes.
I've finished the CFFI variant and been preparing a new release. If GIL really matters, you might want to try PyPy and xxhash CFFI variant.

**Comment by thedrow** [comment]
Thanks. I didn't have the time to test this unfortunately. 
I'll check out the cffi extension.

**Comment by ifduyue** [comment]
@thedrow No problem.

**Comment by pitrou** [comment]
See PR #22.
