### ISSUE TITLE
CFFI variant can't hash numpy.array

### ISSUE THREAD

**Issue by ifduyue** [ifduyue/python-xxhash#14]

**Comment by pitrou** [comment]
Should be fixed by PR #21

**Comment by pitrou** [comment]
Now fixed:
```
>>> import numpy as np
>>> a = np.ones(5)
>>> import xxhash
>>> xxhash.cffi.xxh64(a).digest()
b'\xf1\xab\xcb\x9c|D.\x94'
```

**Comment by ifduyue** [comment]
I'm thinking whether this is too much.
Since we can always xxhash(a_numpy_array.data).

The cpython variant uses PyArg_ParseTupleAndKeywords with 'S*' and this is why it can xxhash(a_numpy_array) directly, while the cffi variant is using PyArg_UnpackTuple.
According to [the docs](https://docs.python.org/3/c-api/arg.html#strings-and-buffers), 'S*' accepts str or bytes-like object.
