### ISSUE TITLE
Memory leak in the CFFI version?

### ISSUE THREAD

**Issue by bra-fsn** [ifduyue/python-xxhash#16]
Running this program:
```
from xxhash import xxh32, xxh64
import time

for a in xrange(100):
  st=time.time()
  for i in xrange(10**6):
    xxh64(str(i))
  print (a, time.time()-st)
time.sleep(60)
```
Uses 4,8 GiB (RES) memory at the end.

The non-CFFI version with cpython remains at 7712K, while with pypy it tops at 68668K.

**Comment by ifduyue** [comment]
According to CFFI docs http://cffi.readthedocs.io/en/latest/ref.html#ffi-gc

> Note that ffi.gc() should be avoided for large memory allocations or for limited resources. This is particularly true on PyPy: its GC does not know how much memory or how many resources the returned ptr holds. It will only run its GC when enough memory it knows about has been allocated (and thus run the destructor possibly later than you would expect). Moreover, the destructor is called in whatever thread PyPy is at that moment, which might be a problem for some C libraries. In these cases, consider writing a wrapper class with custom __enter__() and __exit__() methods, allocating and freeing the C data at known points in time, and using it in a with statement.

I think it's not a memory leak, but rather PyPy doesn't run GC yet.
I will follow the note, get rid of ffi.gc, and see if it can alleviate the memory occupation problem.

**Comment by ifduyue** [comment]
@bra-fsn try commit 75a3fec

I highly recommend to create a xxh32/xxh64 object and reuse it.  Calling the ``.reset()`` method and it's like a new one.

**Comment by ifduyue** [comment]
https://pypi.python.org/pypi/xxhash/1.0.1 released
