### ISSUE TITLE
CFFI advantages

### ISSUE THREAD

**Issue by davidt99** [ifduyue/python-xxhash#18]
It's a question rather than an issue.
Is CFFI faster than cpython version? If not, what are the advantages of using CFFI version?

**Comment by ifduyue** [comment]
Hello, 

CFFI variant is for PyPy, http://pypy.org/compat.html says ``PyPy has alpha/beta-level support for the CPython C API, however, this feature is not yet complete. We strongly advise use of CFFI instead. CFFI come builtin with PyPy. ``

However, I haven't benchmark it, maybe it's faster, maybe not.

**Comment by ifduyue** [comment]
Relating issue https://github.com/ifduyue/python-xxhash/issues/10

**Comment by davidt99** [comment]
Thanks for the info
