### ISSUE TITLE
New relase on conda-forge

### ISSUE THREAD

**Issue by gsakkis** [ifduyue/python-xxhash#26]
The conda-forge release of xxhash is almost 2 years old; would be great to update it to the latest v1.3.0.

**Comment by ifduyue** [comment]
@gsakkis Hello, did you mean this one at https://anaconda.org/conda-forge/python-xxhash ?
I'm not afflicated with conda-forge and I'm not familiar with their build system, so there isn't much I can do.
However, even we're under a conda environment, we can still run ``pip install xxhash`` and get this package directly from PyPI.

**Comment by gsakkis** [comment]
@ifduyue yes, that's the one. I'm not familiar with the details either but I think it's built automatically from https://github.com/conda-forge/python-xxhash-feedstock; it could be as simple as changing the [version](https://github.com/conda-forge/python-xxhash-feedstock/blob/master/recipe/meta.yaml#L1) if nothing else changed in the dependencies or build process. Perhaps I should ping  @mariusvniekerk instead as the recipe maintainer. Until then I can install it from pip, you're right.

**Comment by ifduyue** [comment]
@gsakkis 1.3.0 is available on https://anaconda.org/conda-forge/python-xxhash, I'm closing this.

**Comment by gsakkis** [comment]
Great, thanks!

**Comment by regaldude** [comment]
> 1.3.0 is available on https://anaconda.org/conda-forge/python-xxhash, I'm closing this

@ifduyue Can this be mentioned in the README for the project?

**Comment by ifduyue** [comment]
@regaldude what's the purpose?

**Comment by regaldude** [comment]
@ifduyue It would have certainly helped me avoid some confusion if the conda installation process was mentioned in the README. 

I would be happy to create a quick PR to add this if you would like.

**Comment by ifduyue** [comment]
@regaldude Did you mean this ` conda install -c conda-forge python-xxhash`?

**Comment by regaldude** [comment]
Yes

**Comment by ifduyue** [comment]
> I would be happy to create a quick PR to add this if you would like.

@regaldude OK, please create a PR
