### ISSUE TITLE
'BufferedReader' does not have the buffer interface

### ISSUE THREAD

**Issue by shadowrylander** [ifduyue/python-xxhash#27]
Hello! <br>
&nbsp;&nbsp;&nbsp;&nbsp; Would it be possible to xxhash a file opened as "read-only binary"? This is my current code:
```python
with open("/home/shadowrylander/include.md", "rb") as file:
    xxhash.xxh32(file).hexdigest()
```
but it gives:
```
      1 with open("/home/shadowrylander/include.md", "rb") as file:
----> 2     xxhash.xxh32(file).hexdigest()

TypeError: 'BufferedReader' does not have the buffer interface
```
&nbsp;&nbsp;&nbsp;&nbsp; How would I go about fixing this? <br>
Thank you kindly for the help!

**Comment by ifduyue** [comment]
Hello, 

There are two ways to calculate the hash of a file:

a) Hash file contents all at once:

```python
with open("/home/shadowrylander/include.md", "rb") as file:
    xxhash.xxh32_hexdigest(file.read())
```

b) Hash file contents chunk by chunk

```python
h = xxhash.xxh32()

with open("/home/shadowrylander/include.md", "rb") as file:
    while True:
        chunk = file.read(32768)
        if not chunk:
            break
        h.update(chunk)

h.hexdigest()
````

**Comment by ifduyue** [comment]
b1) Hash file contents chunk by chunk using iterator

```python
h = xxhash.xxh32()

with open("/home/shadowrylander/include.md", "rb") as file:
    for chunk in iter(lambda: file.read(32768), b''):
        h.update(chunk)

h.hexdigest()
```

**Comment by shadowrylander** [comment]
Thank you! Two quick questions, if possible:
1. Would chunking take more memory and / or processing power?
2. How frequent are hash collisions? Is there any way I can set how long a hash value is?

**Comment by ifduyue** [comment]
1. If file is very large, yout don't want to read its content in memory, then use the chunk by chunk method.
2. Please refer to https://github.com/Cyan4973/xxHash/issues/156#issuecomment-437712798

**Comment by shadowrylander** [comment]
Thank you again! One last question: In your opinion, what digest method should I use for the least chances of collisions, or are they all the same?

**Comment by shadowrylander** [comment]
Thank you once again! Though I meant `intdigest`, `hexdigest`, etc. I'll close this issue now!

**Comment by ifduyue** [comment]
Glad to help.
xxhash lib itself returns integer. In python-xxhash I've added digest and hexdigest along with intdigest. They are all the same but in different presentations, hexdigest is hex chars, intdigest is integer, and digest is binary. 

```python
>>> xxhash.xxh64_hexdigest('')
'ef46db3751d8e999'
>>> xxhash.xxh64_intdigest('')
17241709254077376921
>>> xxhash.xxh64_digest('')
b'\xefF\xdb7Q\xd8\xe9\x99'
>>> format(17241709254077376921, 'x')
'ef46db3751d8e999'
>>> binascii.hexlify(b'\xefF\xdb7Q\xd8\xe9\x99')
b'ef46db3751d8e999'
>>> int('ef46db3751d8e999', 16)
17241709254077376921
```

**Comment by shadowrylander** [comment]
Ah! Right. I plan to use `intdigest` with numpy to create an index, as it seems to be faster with numbers than true python; if a hash, or the order of the list, changes, the check for file change has failed, and the function returns a true.
