### ISSUE TITLE
128 bits ?

### ISSUE THREAD

**Issue by drandreaskrueger** [ifduyue/python-xxhash#34]
I am trying the https://www.shawntabrizi.com/substrate/querying-substrate-storage-via-rpc/#querying-runtime-storage manual in Python.

Look [what they have decided to use in polkadot/substrate](https://www.shawntabrizi.com/substrate/querying-substrate-storage-via-rpc/#storage-value-query):

> Note: Note that we specified to use the 128 bit version of XXHash.

I am trying to replicate all their JavaScript stuff into Python:

    import xxhash # pip install xxhash
    
    U8a = bytes("Sudo Key", encoding='utf8')
    print (list(U8a))

    print (xxhash.xxh32(U8a).hexdigest()) 
    print (xxhash.xxh64(U8a).hexdigest())
    print (xxhash.xxh128(U8a).hexdigest())

but ... what I get is:

> [83, 117, 100, 111, 32, 75, 101, 121]  
> ae5549fb  
> 2ed2ce1a873aa650  
> AttributeError: module 'xxhash' has no attribute 'xxh128'  

Not sure I understand this correctly, but it looks as if  
xxhash( _ , 128) == xxh128( _ )  
right?  

**Could you please implement that for us? Thank you very much!**

Versions:

    xxhash.VERSION 1.3.0 
    xxhash.XXHASH_VERSION 0.6.5

**Comment by drandreaskrueger** [comment]
Hahaha:

https://matrix.to/#/!HzySYSaIhtyWrwiwEV:matrix.org/$157418514657326zulFO:matrix.org?via=matrix.parity.io&via=matrix.org&via=web3.foundation

**Comment by drandreaskrueger** [comment]
now that's what I call a funny outcome of a totally misunderstood problem:

![Screenshot from 2019-11-20 01-27-12_smaller](https://user-images.githubusercontent.com/7796035/69198672-bcfb9d00-0b35-11ea-9a6f-b9da3910d658.jpg)

ahhhh

![Screenshot from 2019-11-20 01-25-40_smaller](https://user-images.githubusercontent.com/7796035/69198675-bff68d80-0b35-11ea-978e-3507c4319f30.jpg)

lolol

bitly --> https://github.com/polkascan/py-substrate-interface/blob/ac8ce4a44b5bffcdbce76e843b2e4991cc44b458/substrateinterface/__init__.py#L227

**Comment by drandreaskrueger** [comment]
> Please call it 2x64 or 64x2 in the future. Or 64x64. or 64+64. 

Thanks.

CanClose.

**Comment by ifduyue** [comment]
Accually, there's 128 bits:

<img width="907" alt="image" src="https://user-images.githubusercontent.com/568900/69206106-c06b4480-0b86-11ea-831b-0803bf006fcc.png">

It's experimental and it's not fronzed. I've created a branch [xxh3](https://github.com/ifduyue/python-xxhash/tree/xxh3) to play with xxh3

**Comment by drandreaskrueger** [comment]
> Actually, there's 128 bits:

Oh. So they were wrong? 

What is the output of 

    import xxhash
    U8a = bytes("Sudo Key", encoding='utf8')
    print (list(U8a))
    print (xxhash.xxh32(U8a).hexdigest()) 
    print (xxhash.xxh64(U8a).hexdigest())
    print (xxhash.xxh128(U8a).hexdigest())

?

---

... because I tried myself, but could not install your branch - what am I doing wrong?

```
source env/bin/activate
git clone https://github.com/ifduyue/python-xxhash.git ifduyue_python-xxhash
cd ifduyue_python-xxhash/
git checkout 5b243ee
python setup.py install
```
results in

> src/_xxhash.c:33:10: fatal error: xxh3.h: No such file or directory
> #include "xxh3.h"

i have tried with this:
```
apt-cache search xxh
# libxxhash-dev - header files and a static library for libxxhash

sudo apt install libxxhash-dev
python setup.py install
```
but ... same.

**Comment by drandreaskrueger** [comment]
hah. found it.

    git submodule init
    git submodule update

now it works.

**Comment by drandreaskrueger** [comment]
or with `--recursive`:
```
source env/bin/activate
git clone --recursive https://github.com/ifduyue/python-xxhash.git ifduyue_python-xxhash
cd ifduyue_python-xxhash/
git checkout 5b243ee
python setup.py install
cd ..
```

**Comment by ifduyue** [comment]
```
git clone --recursive --branch xxh3 https://github.com/ifduyue/python-xxhash
cd python-xxhash
python setup.py build_ext --inplace
```

```python
import xxhash

print("xxh3_64")
print("\t", repr(xxhash.xxh3_64_digest('a')))
print("\t", xxhash.xxh3_64_hexdigest('a'))
print("\t", xxhash.xxh3_64_intdigest('a'))

print("xxh3_128")
print("\t", repr(xxhash.xxh3_128_digest('aa')))
print("\t", xxhash.xxh3_128_hexdigest('aa'))
print("\t", xxhash.xxh3_128_intdigest('aa'))
```

output:
```
xxh3_64
	 '\x88\xd8h\xbf`v\x81\xc7'
	 88d868bf607681c7
	 9860746555294122439
xxh3_128
	 '\xbe\xe5\x97\x1d\xfeQ\xf5\xfe\xc6f\x014\x12n+\x01'
	 bee5971dfe51f5fec6660134126e2b01
	 13755566791949678078
```

**Comment by ifduyue** [comment]
Currently only oneshot functions are implemented, i.e. `xxh3_64_digest` `xxh3_64_hexdigest` `xxh3_64_intdigest` `xxh3_128_digest` `xxh3_128_hexdigest` `xxh3_128_intdigest`

**Comment by drandreaskrueger** [comment]
Great, thanks! 

Yes, I could now get these answers myself:

```
import xxhash 

def xxh6464(x):
    o1 = bytearray(xxhash.xxh64(x, seed=0).digest())
    o1.reverse()
    o2 = bytearray(xxhash.xxh64(x, seed=1).digest())
    o2.reverse()
    return "0x{}{}".format(o1.hex(), o2.hex())

U8a = bytes("Sudo Key", encoding='utf8')
print (xxhash.xxh32_hexdigest(U8a)) 
print (xxhash.xxh64_hexdigest(U8a))
print (xxhash.xxh3_128_hexdigest(U8a))
print (xxh6464(U8a))
```
results in:

> ae5549fb
> 2ed2ce1a873aa650
> 54f1ae501c4535c2228b6752a3794f3f
> 0x50a63a871aced22e88ee6466fe5aa5d9

and 54f1ae501c4535c2228b6752a3794f3f is not 0x50a63a871aced22e88ee6466fe5aa5d9

what they said [there](https://www.shawntabrizi.com/substrate/querying-substrate-storage-via-rpc/#storage-value-query)

    util_crypto.xxhashAsHex(util.stringToU8a("Sudo Key"), 128)
    > "0x50a63a871aced22e88ee6466fe5aa5d9"

perhaps should they better rename their `util_crypto.xxhashAsHex( ___ , 128)` ?

**Comment by ifduyue** [comment]
> and 54f1ae501c4535c2228b6752a3794f3f is not 0x50a63a871aced22e88ee6466fe5aa5d9


xxh3_128 is a new algorithm, so this is expected. If they concatenate two xxh64 digest to get a 128 bits hash, you should do it in the same way in order to get the same result.

When I mentioned 128 bits hashes above, I was thinking that xxh3 is a better way to generate a 128 bits hash. Unfortunately xxh3 algorithm is not frozen yet, we have to wait.

**Comment by drandreaskrueger** [comment]
Thanks a lot. Truly great that you reacted so quickly. Much appreciated.

I have now reported it back into [their riot chat](https://matrix.to/#/!HzySYSaIhtyWrwiwEV:matrix.org/$1574245068226385NMVlF:matrix.org?via=matrix.parity.io&via=matrix.org&via=web3.foundation), so that they know.

**Comment by ifduyue** [comment]
You're welcome
