### ISSUE TITLE
xxhash 0.8 released (and xxh3 support)

### ISSUE THREAD

**Issue by levic** [ifduyue/python-xxhash#38]
0.8 was released a week ago and xxh3 is now stable: https://github.com/Cyan4973/xxHash/releases/tag/v0.8.0

Hopefully this means that the xxh3 experimental branch in #34 can be merged into master and a new release pushed out to pypi?

Thanks for these bindings -- the lack of 128 bit support had ruled out xxhash for my use case, and would love to try it out

**Comment by ifduyue** [comment]
@levic v2.0.0 just released. https://pypi.org/project/xxhash/2.0.0/
