### ISSUE TITLE
Missing Python 3.9 wheel

### ISSUE THREAD

**Issue by arjanz** [ifduyue/python-xxhash#43]
Hi, I saw the Python 3.9 binary is missing on PyPI, will this be release any time soon?

Thanks!

**Comment by bashtage** [comment]
It would be great to get a 3.9 wheel!

**Comment by m-stefanski** [comment]
+1 for Python 3.9 support

**Comment by sadamasin** [comment]
+1 for Python 3.9 support

**Comment by ifduyue** [comment]
Noticed.  In two or three weeks I'll make a new release.

**Comment by ifduyue** [comment]
2.0.2 released https://pypi.org/project/xxhash/2.0.2/
