### ISSUE TITLE
__init__.py file in ./tests breaks pytest imports

### ISSUE THREAD

**Issue by essandess** [ifduyue/python-xxhash#45]
The existence of `__init__.py` in [tests](../blob/master/tests/__init__.py) breaks imports from `pytest`, a known issue.

See:
* https://docs.pytest.org/en/stable/pythonpath.html
* https://stackoverflow.com/questions/41748464/pytest-cannot-import-module-while-python-can
* https://stackoverflow.com/questions/10253826/path-issue-with-pytest-importerror-no-module-named-yadayadayada
* https://github.com/macports/macports-ports/pull/10316#discussion_r597778553

**Comment by ifduyue** [comment]
Removing tests/__init__.py breaks tests on windows, see https://ci.appveyor.com/project/duyue/python-xxhash/builds/38702729
Any suggestions?

**Comment by ifduyue** [comment]
Removed in v3 branch, swithed to py.test 407e6367159a1ae10b71f10f859bf5e1218aaab4
