### ISSUE TITLE
Wheel for new MacOS M1 arch

### ISSUE THREAD

**Issue by arjanz** [ifduyue/python-xxhash#46]
Is it possible to compile the wheels for the new MacOS M1 ARM chip? (E.g. `xxhash-2.0.2-cp3.9-cp3.9-macosx_11_0_arm64.whl`)

The current binaries are incompatible unfortunately.

**Comment by ifduyue** [comment]
Sure. It seems cibuildwheel has MacOS M1 support. I'll work on this when I have more time. 
Meanwhile PR is welcome.

**Comment by ifduyue** [comment]
New release 3.0.0 is on PyPI now
