### ISSUE TITLE
API Compatibility with haslib

### ISSUE THREAD

**Issue by hmaarrfk** [ifduyue/python-xxhash#48]
Hello,

I'm trying to add support for using xxhash in an other project as an alternative to algorithms provided by hashlib.

I'm hoping that I could make some PRs to enhance the compatibility between the two.

Specifically, i'm looking to add a set `xxhash.algorithms_available` similar to

* https://docs.python.org/3/library/hashlib.html#hashlib.algorithms_available

Let me know if making this PR would be OK.

**Comment by ifduyue** [comment]
@hmaarrfk PR is welcome. Please go ahead and send a PR.
