### ISSUE TITLE
Cannot import xxhash: `ModuleNotFoundError: No module named 'xxhash._xxhash`

### ISSUE THREAD

**Issue by drinkitup777** [ifduyue/python-xxhash#50]
After the latest release `2.0.2`, importing `xxhash` from Python 3.10.0 on Windows 10 x64 produces the following error:

```python
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import xxhash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Extra\Python3\lib\site-packages\xxhash\__init__.py", line 1, in <module>
    from ._xxhash import (
ModuleNotFoundError: No module named 'xxhash._xxhash'
```

The `2.0.1` release still works fine. There must have been some change in the packaging that's causing this.

**Comment by surya-gaurav** [comment]
I am also running with the same error. Tried with all the versions including `2.0.0`, `2.0.1` and even `2.0.2`. I am using Python `3.8.1`.

**Comment by dulfox** [comment]
> Python 3.10.0

AFAIK it is not supported yet.

**Comment by ifduyue** [comment]
I'm working on this

**Comment by ifduyue** [comment]
I can't replicate this error. Though I'm using Python 3.10.1.

```python
Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import xxhash
>>> xxhash.VERSION
'2.0.2'


Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import xxhash
>>> xxhash.VERSION
'2.0.1'
```

**Comment by ifduyue** [comment]
2.0.1 and 2.0.2 basically have no differences, except that I fixed a bug regarding building Mac OS wheels.

**Comment by ifduyue** [comment]
New release 3.0.0 is on PyPI now. Windowns x64 wheels are provided.

**Comment by drinkitup777** [comment]
The issue is gone with xxhash 3.0.0 and Python 3.10.2. Whatever was causing the issue seems to have resolved itself.
