### ISSUE TITLE
Ascii representation of the hash

### ISSUE THREAD

**Issue by dulfox** [ifduyue/python-xxhash#53]
Could you please provide a way to show _directly_ the **ascii** representation of the hash as the output from xxhash binary ?

Or at least show an example of code to display it as the binary ?

Here is an example to show what I meant : 

import xxhash
import binascii
fname="sample.txt"
with open(fname,'rb') as f:
    h1=xxhash.xxh3_128_digest(f.read(), seed=0)
print(binascii.b2a_hex(h1).decode(),fname)

**Comment by ifduyue** [comment]
@dulfox does  `h1.hexdigest()`  meet your requirements?

**Comment by dulfox** [comment]
Unfortunately no.
I want the same output as the xxhash gives:
For instance, if sample.txt contains "This is a text file",
xxh128sum gives '7231fbaa074cfa1e73582c2898fc1f0e' as a result and 
xxhash.xxh3_128_hexdigest() ouputs '99aa06d3014798d86001c324468d497f' 
which are not the same.

Maybe I don't know how to use it and don't hesitate to correct me if I'm wrong.

**Comment by ifduyue** [comment]
```python
>>> import xxhash
>>> xxhash.xxh3_128_hexdigest(open('sample.txt', 'rb').read())
'7231fbaa074cfa1e73582c2898fc1f0e'
```

I tried and the hash results were the same. Did you open the file in binary mode?

**Comment by dulfox** [comment]
Maybe I've done it wrong. Thanks for your explanation and your time.

**Comment by dulfox** [comment]
Works perfectly with hexdigest in binary mode.
