### ISSUE TITLE
Python 3.10 wheel

### ISSUE THREAD

**Issue by EpicWink** [ifduyue/python-xxhash#54]
Feature request: build Python 3.10 wheel for all supported platforms (manylinux2010 / manylinux1 / Windows / macOSX 10; PyPy v3.10 isn't released, and macOS 11 and musllinux aren't yet supported). This will allow installation in environments without a C compiler

Current workaround for Debian-based Linux: `apt install gcc libc-dev --no-install-recommends gcc libc-dev`

Edit: as far as I can tell, `cibuildwheel` will automatically build a Python 3.10 wheel on next release

**Comment by ifduyue** [comment]
Hello, 

3.0.0 just released.
