### ISSUE TITLE
Musllinux wheels

### ISSUE THREAD

**Issue by nakata5321** [ifduyue/python-xxhash#57]
Hi! I'm work with Home Assistant OS and now I'm working with your library. Home Assistant OS is build on Alpine, which is musllinux system. And on OS i can not build your library without wheels.
Could you explain, why in your 'pyproject.toml' you skip musllinux implementation? 
If it possible to delete this rule and build wheels for musllinux?

**Comment by ifduyue** [comment]
Can't remember why, maybe it was not stable at the time when we switched to cibuildwheel.

**Comment by nakata5321** [comment]
But now it is stable and it is working. I built your libraries wheel on RPI4 with HomeAssistant OS on it(it's musllinux) a week ago and everything was working well. 
So, could you check now muslwheels one more time, and if everything OK, then upload them to PYPI?

**Comment by nakata5321** [comment]
I really need this wheels, because by default HomeAssistant OS doesn't install gcc, so i can not install my integration(which use your library) from the box. And HomeAssistant OS doesn't allow to install side packages.

**Comment by ifduyue** [comment]
OK, we can remove those skip rules.

**Comment by nakata5321** [comment]
OK, first, thank you very match for help and answer.
But I can not find new wheels on PyPI... I see, that you merge update into the master and action has been built.
Action has built them with tag - `xxhash-3.0.1.dev4-cp310..`. Maybe because of this `dev4` part they didn't uploaded to PyPI? On PyPI is still `3.0.0` the latest [release](https://pypi.org/project/xxhash/). 

Maybe you have to create a minor release?

**Comment by ifduyue** [comment]
released https://pypi.org/project/xxhash/3.1.0/
