### ISSUE TITLE
setuptools' test command is deprecated

### ISSUE THREAD

**Issue by stanislavlevin** [ifduyue/python-xxhash#58]
`setup.py test` is deprecated since setuptools 41.5.0:
https://setuptools.pypa.io/en/latest/history.html#v41-5-0

See https://github.com/pypa/setuptools/issues/1684 for details.

**Comment by ifduyue** [comment]
@stanislavlevin Thanks for this info.

**Comment by ifduyue** [comment]
Switched to `python -m unittest discover -vv tests` in 70411dc
