### ISSUE TITLE
Request: add a reset() method?

### ISSUE THREAD

**Issue by congma** [ifduyue/python-xxhash#6]
Hi,

I think it would be great if there's a `reset()` method for `xxh32/64` objects, which clears the slate so the next `update()` call begins anew.  This shouldn't hurt `hashlib` compatibility I think.

What do you think?

--cong.

**Comment by ifduyue** [comment]
Sounds reasonable to me

**Comment by ifduyue** [comment]
Done. https://pypi.python.org/pypi/xxhash/0.4.0
