### ISSUE TITLE
Feature request: add xxhash to Pyodide

### ISSUE THREAD

**Issue by jpivarski** [ifduyue/python-xxhash#65]
This would allow libraries that depend on xxhash to run in JupyterLite, py-script, etc.

Packages are added to Pyodide by explicitly compiling them in; there's a [large directory of those packages](https://github.com/pyodide/pyodide/tree/main/packages), and they're each governed by a meta.yaml and a small test. [Here is an example of a meta.yaml file](https://github.com/pyodide/pyodide/blob/main/packages/awkward-cpp/meta.yaml): it has a URL to the source tarball of the latest version of the package and provides environment variables (or other helpers) for the build process. Whenever a new source tarball is pushed to PyPI, [a bot writes its own PR to update this meta.yaml](https://github.com/pyodide/pyodide/pull/4589).

**Comment by ifduyue** [comment]
PR https://github.com/pyodide/pyodide/pull/4669

**Comment by ifduyue** [comment]
pyodide merged my PR, I'm going to close this.
