### ISSUE TITLE
question: where is the code of xxh3_128 function

### ISSUE THREAD

**Issue by m0x61h0x64i** [ifduyue/python-xxhash#77]
Hi, i have a question: where is the code of xxh3_128 function?
Im going to read it and write a function to do reverse job of xxh3_128 function.
Thanks

**Comment by ifduyue** [comment]
Hi @m0x61h0x64i 
This is a python binding of https://github.com/Cyan4973/xxHash.
What do you mean to do a reverse job of xxh3_128? It's not designed to be reversed.

**Comment by m0x61h0x64i** [comment]
> It's not designed to be reversed.

Thanks
